### ISSUE TITLE
Bug of GS-SCF convergence in the current/recent version (ARTED side)

### ISSUE THREAD

**Issue by ayamada224** [SALMON-TDDFT/SALMON#179]
I found a bug of ground-state scf calculation in ARTED side in the current/recent version (not in the older version: at least around two weeks ago).
(double check was done by Uemoto-san)

In the current version, the scf does not converge like (XX_GS.out):
 ...............
   148   -0.4379181722E+03    0.7835661139E-02    0.8154006743E-02    0.2362924103E-01
   149   -0.4380639074E+03    0.4877358546E-02    0.6855756716E-02    0.1908358073E-01
   150   -0.4379719259E+03    0.5001770535E-02    0.7146741877E-02    0.2145845483E-01

but on the other hand scf converges with the older version (of around the end of August):
.............
   148   -0.4384640347E+03    0.1445445105E-09    0.2410829159E-08    0.1922763162E-07
   149   -0.4384640347E+03    0.2467451177E-09    0.3026866230E-08    0.1054536409E-05
   150   -0.4384640347E+03    0.2446715902E-09    0.2720838887E-08    0.9017800164E-06

I'm going to fix this issue with Uemoto-san. 
If you know something about that please let us know.

best, 
A-Yamada

**Comment by uemoto1** [comment]
Thank you @ayamada224 for bug report.

I also confirmed the above problem in recent version of SALMON.

Now I have submitted a job to search the first version causes this problem with rolling back the git histories. For now, I narrowed down the beginning of bug is one of pull request between PR#164-177.  I need a bit time to identify the single pull requests.

**Comment by uemoto1** [comment]
I have obtained the result of calculations and identified the related pull request (PR #175). After merging this PR,  the decreasing of the convergency appears in the numerical results. I suggest checking the implementation of PR and (if it is necessary) reverting the merge commitment.

|Commit|Pull Request| Total energy (iter=100)| Delta E (iter=100)|
|:--|:--|:--|:--|
|3760346|Merge pull request #177|-31.1644588347157|-8.162118815171482E-004
|077efe5|Merge pull request #176|-31.1704499164816|-3.352016921326140E-003
|503b107|Merge pull request #175|-31.1695048636110|-1.105028257521923E-002
|e0f77a3|Merge pull request #173|-31.2658878785857|-1.240643143773923E-009
|409ffcb|Merge pull request #172|-31.2658878785857|-1.240643143773923E-009
|4a98673|Merge pull request #170|-31.2658878785857|-1.240643143773923E-009
|d5fcd81|Merge pull request #169|-31.2658878785857|-1.240643143773923E-009
|d0f967a|Merge pull request #166|-31.2658878785857|-1.240643143773923E-009
|72cad62|Merge pull request #165|-31.2658878785857|-1.240643143773923E-009
|f3d1a62|Merge pull request #164|-31.2658878785857|-1.240643143773923E-009
|1d03a53|Merge pull request #163|-31.2658878785857|-1.240643143773923E-009
|be84eeb|Merge pull request #162|-31.2658878844389|1.034230479035614E-009
|176863c|Merge pull request #160|-31.2658878844389|1.034230479035614E-009

- The used input file is uploaded as below:
https://gist.github.com/uemoto1/0e6f40338802a45d7c6ab55c84e9af6e

**Comment by yhirokawa-ccs** [comment]
@uemoto1 san and @ayamada224 san, I read src/ARTED/GS/diag.f90 which modified by PR #175.
Probably, line 89-92 happens OpenMP thread conflict.
For quick fix, I suggest `!$omp end parallel` clause at line 94 moves to line 88.

**Comment by uemoto1** [comment]
Thank you @yhirokawa san. I grasped the point of this problem. I will send the bug fix immediately.

**Comment by mn2007** [comment]
Sorry for having embedded the bug. I wait the bug fix @uemoto san will give.
