### ISSUE TITLE
Build by gfortran

### ISSUE THREAD

**Issue by uemoto1** [SALMON-TDDFT/SALMON#225]
Currently, the build of SALMON in gfortran is difficult because of the version of GCC.
The present SALMON requires `use ieee_arithmetic` in `SALMON/src/ARTED/modules/performance_analyzer.f90`. 
However, `ieee_arithmetic` is only supported the gfortran later than version 5.

Our test environment uses the GCC as below:
- `GCC 4.8.5` (Jenkins machine)
- `GCC 4.8.5` (OFP)
- `GCC 4.4.7` (COMA)
- `GCC 4.8.5` (Sekirei@ISSP)

Besides, the not small number of the package management system in the operating system uses  v.4.8.  Therefore, I think the most of the workstation on the end users environment is difficult to use gnu compiler builds. Can we modify the SALMON without using `ieee_arithmetic` module?

(Presently, I did not confirm how it works in the gfortran)

**Comment by yhirokawa-ccs** [comment]
@uemoto1 san, thank you for reviewing and merging PR #228.
Your PR #230 which a patch for GNU Make was merged, and I close this issue.
