### ISSUE TITLE
error  in compiling SALMON

### ISSUE THREAD

**Issue by tmisawa** [SALMON-TDDFT/SALMON#301]
Dear developers of SALMON

Now, I am trying to compile SALMON
in the supercomputer @ ISSP (sekirei).

Below commands are what I did for the compiling.
```
mkdir build 
cd ./build
python ../configure.py  --prefix=../
make
``` 

In the compiling process,
compiling stops with the below error messages.
```
/home/i0411/i041101/Git/SALMON/src/GCEED/rt/calc_current.f90(147): error #6285: 

There is no matching specific subroutine for this generic subroutine call.  [COMM_SUMMATION]

call comm_summation(uVpsibox1_j,uVpsibox2_j,4*maxlm*MI*iobnum*k_num,nproc_group_korbital)
-----^

compilation aborted for /home/i0411/i041101/Git/SALMON/src/GCEED/rt/calc_current.f90 (code 1)

```

What is wrong ?
If you have any ideas for solving the error,
please tell me.

Best,
Takahiro Misawa

**Comment by uemoto1** [comment]
Dear Takahiro,

Thank you for interest in SALMON codes.

I guess the configure script might fail to detect the MPI library.
Thus, I recommend to check the following 2 points about the environment:

1. Import the compiler and libraries before configulation.
If you use the sekirei in SYSTEM-B, you can specify them by module command:
```
module load intel intel-mpi intel-mkl
```

2. Specify the architecture switch
We also have `--arch` switch to specify the architecture of the system;
```
python ../configure.py  --prefix=../ --arch=intel-avx2
```

**Comment by tmisawa** [comment]
Dear uemoto1,

Thank you for quick and kind reply.
By following your suggestions,
I have succeeded in compiling without error !

Best,
Takahiro Misawa
